#!/usr/bin/env bash
#
# mayhem/build.sh — build the XXL interpreter fuzz target + reproducer + upstream test suite.
#
# XXL is a small tree-walking interpreter. The fuzz surface is the reader+evaluator driven over
# STDIN: with no args main() falls through to repl(), which parses+evaluates each form read from
# stdin until EOF and exits (the shape of the original mayhemheroes target, which covered edges;
# an `xxl @@` file-arg target recorded 0). The same binary doubles as the run-once reproducer
# (`xxl <file>` evaluates a file and exits when stdout isn't a tty). It is built SINGLE-THREADED
# (no -DTHREAD, and no STDLIBMBOX, whose mailboxes require threads): the interpreter core doesn't
# need threads to parse+evaluate input, and single-threaded sanitized CLI binaries are the
# fleet-proven fuzzable shape for interpreters. The upstream test suite is
# xxl's built-in selftest (test_basics/nest/ctx/eval/logic/semantics, run when built -DDEBUG and
# invoked with no args) and keeps upstream's full -DTHREAD configuration.
set -euo pipefail

[ -n "${SOURCE_DATE_EPOCH:-}" ] || unset SOURCE_DATE_EPOCH

: "${SANITIZER_FLAGS=-fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer}"
: "${DEBUG_FLAGS:=-g -gdwarf-3}"
: "${CC:=clang}"
: "${MAYHEM_JOBS:=$(nproc)}"
: "${COVERAGE_FLAGS=}"
export SANITIZER_FLAGS DEBUG_FLAGS CC MAYHEM_JOBS COVERAGE_FLAGS

cd "$SRC"

SRCS="xxl.c repl.c net.c stdlib.c verbs.c"
# Enabled stdlib modules (mirror the upstream ./c build script's default LIBRARIES set).
LIBDEFS="-DOCTA -DSTDLIBFILE -DSTDLIBGLOB -DSTDLIBMBOX -DSTDLIBNET -DSTDLIBSHAREDLIB -DSTDLIBSHELL -DSTDLIBXD"
# Fuzz-binary module set: everything except STDLIBMBOX (mailboxes hard-require -DTHREAD).
FUZZ_LIBDEFS="-DOCTA -DSTDLIBFILE -DSTDLIBGLOB -DSTDLIBNET -DSTDLIBSHAREDLIB -DSTDLIBSHELL -DSTDLIBXD"
# Upstream is pre-C99 GNU C (uses `auto`/implicit-int, implicit function decls). clang-19 defaults to
# C23 where those are hard errors, so pin the GNU C17 dialect (matches the upstream ./c gcc build) and
# silence the remaining benign warnings so -w keeps the log readable; not correctness-affecting.
STD="-std=gnu17"
# clang-19 promotes these pre-C99 constructs from warnings to hard errors; upstream relies on them
# (gcc accepts them). Explicitly demote to non-errors (-w alone can't disable default-error diags).
COMPAT="-Wno-implicit-int -Wno-implicit-function-declaration -Wno-int-conversion -Wno-error=implicit-int -Wno-error=implicit-function-declaration"
WARN="-w $COMPAT"
LINK="-pthread -ldl -lm"

# compile.h is generated by upstream's ./c script; it records the build's own compile commands.
# Regenerate it here (idempotent) so xxl.c #include "compile.h" resolves without invoking node.
gen_compile_h() {
  cat > compile.h <<EOF

#define XXL_SRC "$SRC/"
#define XXL_COMPILEOBJ "$CC -c "
#define XXL_COMPILESHARED "$CC -fPIC -shared "
#define XXL_BUILDOBJ "$CC -o "
#define XXL_BUILDSHARED "$CC -fPIC -shared "
EOF
}
gen_compile_h

# 1) Fuzz target == run-once reproducer: the real interpreter, instrumented (ASan+UBSan) and carrying
#    DWARF<4. Built WITHOUT -DDEBUG so `xxl <file>` takes the evalfile path (no selftest) and exits.
#    Mayhem drives it as `xxl @@`; each input is a fresh process, and detect_leaks=0 is baked in via
#    mayhem/asan_default_options.c (this allocate-and-exit VM never frees its workspace).
$CC $STD $SANITIZER_FLAGS $DEBUG_FLAGS $WARN $FUZZ_LIBDEFS $SRCS mayhem/asan_default_options.c -ldl -lm -o /mayhem/xxl

# 2) Upstream test suite: xxl built -DDEBUG runs its built-in assertion selftest when given no args.
#    Built with the project's NORMAL flags (no sanitizers) so test.sh is an honest functional oracle;
#    append $COVERAGE_FLAGS (empty by default) for optional coverage measurement of the suite.
gen_compile_h
$CC $STD -O1 $COVERAGE_FLAGS -DTHREAD -DDEBUG $WARN $LIBDEFS $SRCS $LINK -o /mayhem/xxl-test

echo "build.sh: built /mayhem/xxl (fuzz+reproducer) and /mayhem/xxl-test (selftest runner)"
